export const products = [
   
    {id:1 ,image: '../../cloth04.jpg', name: 'T-Shirt', price: 29.99,category: 'clothes',Model:'AX105',ProductType:'Men',Size:'M',Material:'Cotton ',Description:'This versatile T-shirt is made from high-quality cotton fabric, offering unmatched comfort and breathability. Perfect for both casual wear and layering, it comes in a variety of colors and sizes. The durable stitching ensures long-lasting wear, while the classic crew neck design keeps it timeless. Ideal for everyday wear or pairing with your favorite jacket.Clothes are essential fashion items that reflect personal style and comfort.'},
    {id:2 , image: '../../Jacket.jpg', name: 'Jacket', price: 120.00, category: 'clothes',Model:'AX109',Size:'L',Material:'Jeans',Description:'Stay warm and stylish with this premium jacket, crafted from durable materials to withstand the elements.Its modern design features multiple pockets for functionality, while the soft inner lining keeps you cozy.Clothes are essential fashion items that reflect personal style and comfort.'},
    {id:3 , image: '../../jeans.jpg', name: 'Jeans', price: 45.00, category: 'clothes',Model:'AX107',Size:'S',Material:'Jeans',Description:'These jeans are designed for a perfect balance of style and comfort. Made with high-quality denim, they offer a snug yet flexible fit, adapting to your movements while maintaining their shape.Clothes are essential fashion items that reflect personal style and comfort.' },
    {id:4 , image: '../../Shirt.jpg', name: 'Shirt', price: 29.99, category: 'clothes',Model:'AX106',Size:'XL',Material:'Cotton',Description:'Elevate your wardrobe with this stylish shirt, made from breathable and lightweight fabric for all-day comfort.Clothes are essential fashion items that reflect personal style and comfort.' },
    {id:5 , image: '../../Shoes1.jpg', name: 'Shoes', price: 59.99, category: 'shoes',Model:'BX108',Size:'7',Material:'Mesh',Description:'Built for performance, these running shoes provide maximum comfort and support for all your athletic endeavors.With a lightweight design and durable sole, they enhance your performance while reducing strain on your feet.Shoes are essential items that offer both comfort and fashion. They come in various styles, including sneakers for casual wear, formal shoes for office or events, and sports shoes for running or training.' },
    {id:6 , image: '../../Shoes2.jpg', name: 'Shoes', price: 68.99, category: 'shoes',Model:'BX107',Size:'8',Material:'Mesh',Description:'Built for performance, these running shoes provide maximum comfort and support for all your athletic endeavors.With a lightweight design and durable sole, they enhance your performance while reducing strain on your feet.Shoes are essential items that offer both comfort and fashion. They come in various styles, including sneakers for casual wear, formal shoes for office or events, and sports shoes for running or training.' },
    {id:7 , image: '../../Shoes3.jpg', name: 'Shoes', price: 47.99, category: 'shoes',Model:'BX105',Size:'9',Material:'Mesh',Description:'Built for performance, these running shoes provide maximum comfort and support for all your athletic endeavors.With a lightweight design and durable sole, they enhance your performance while reducing strain on your feet.Shoes are essential items that offer both comfort and fashion. They come in various styles, including sneakers for casual wear, formal shoes for office or events, and sports shoes for running or training.' },
    {id:8 , image: '../../Shoes4.jpg', name: 'Shoes', price: 41.99, category: 'shoes',Model:'BX105',Size:'7',Material:'Mesh',Description:'Built for performance, these running shoes provide maximum comfort and support for all your athletic endeavors.With a lightweight design and durable sole, they enhance your performance while reducing strain on your feet.Shoes are essential items that offer both comfort and fashion. They come in various styles, including sneakers for casual wear, formal shoes for office or events, and sports shoes for running or training.' },
    {id:9 , image: '../../Watch1.jpg', name: 'Watch', price: 99.99, category: 'watches',Model:'CX109',Size:'40mm',Material:'Stainless Steel',Description:'Built for active lifestyles, this sports watch offers a rugged design with water resistance and a range of features like a stopwatch, alarm, and backlight.Watches are both functional and stylish accessories. They come in a variety of designs to suit different tastes, ranging from classic analog models with leather or metal bands to modern digital and smartwatches.'},
    {id:10 , image: '../../Watch2.jpg', name: 'Watch', price: 175.99, category: 'watches',Model:'CX107',Size:'38mm',Material:'Stainless Steel',Description:'Built for active lifestyles, this sports watch offers a rugged design with water resistance and a range of features like a stopwatch, alarm, and backlight.Watches are both functional and stylish accessories. They come in a variety of designs to suit different tastes, ranging from classic analog models with leather or metal bands to modern digital and smartwatches.' },
    {id:11 , image: '../../Watch3.jpg', name: 'Watch', price: 104.99, category: 'watches',Model:'CX105',Size:'36mm',Material:'Stainless Steel',Description:'Built for active lifestyles, this sports watch offers a rugged design with water resistance and a range of features like a stopwatch, alarm, and backlight.Watches are both functional and stylish accessories. They come in a variety of designs to suit different tastes, ranging from classic analog models with leather or metal bands to modern digital and smartwatches.' },
    {id:12 , image: '../../Watch4.jpg', name: 'Watch', price: 119.99, category: 'watches',Model:'CX108',Size:'34mm',Material:'Stainless Steel',Description:'Built for active lifestyles, this sports watch offers a rugged design with water resistance and a range of features like a stopwatch, alarm, and backlight.Watches are both functional and stylish accessories. They come in a variety of designs to suit different tastes, ranging from classic analog models with leather or metal bands to modern digital and smartwatches.' },
  ];